//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.12 at 12:03:42 PM MST 
//
/**
 * Copyright (C) 2014 Cohesive Integrations, LLC (info@cohesiveintegrations.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package net.di2e.ddf.argo.jaxb;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="respondTo" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="respondToPayloadType" type="{}payloadType"/>
 *         &lt;element name="serviceContractID" type="{http://www.w3.org/2001/XMLSchema}anyURI" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="contractID" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "respondTo",
        "respondToPayloadType",
        "serviceContractID"
})
@XmlRootElement(name = "probe")
public class Probe {

    @XmlElement(type = String.class)
    @XmlSchemaType(name = "anyURI")
    protected String respondTo;
    protected PayloadType respondToPayloadType;
    @XmlElement(type = String.class)
    @XmlSchemaType(name = "anyURI")
    protected List<String> serviceContractID;
    @XmlAttribute(name = "id", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String id;
    @XmlAttribute(name = "contractID", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String contractID;

    /**
     * Gets the value of the respondTo property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRespondTo() {
        return respondTo;
    }

    /**
     * Sets the value of the respondTo property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRespondTo( String value ) {
        this.respondTo = value;
    }

    /**
     * Gets the value of the respondToPayloadType property.
     *
     * @return possible object is
     * {@link PayloadType }
     */
    public PayloadType getRespondToPayloadType() {
        return respondToPayloadType;
    }

    /**
     * Sets the value of the respondToPayloadType property.
     *
     * @param value allowed object is
     *              {@link PayloadType }
     */
    public void setRespondToPayloadType( PayloadType value ) {
        this.respondToPayloadType = value;
    }

    /**
     * Gets the value of the serviceContractID property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the serviceContractID property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getServiceContractID().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     */
    public List<String> getServiceContractID() {
        if ( serviceContractID == null ) {
            serviceContractID = new ArrayList<String>();
        }
        return this.serviceContractID;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setId( String value ) {
        this.id = value;
    }

    /**
     * Gets the value of the contractID property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getContractID() {
        return contractID;
    }

    /**
     * Sets the value of the contractID property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setContractID( String value ) {
        this.contractID = value;
    }

}
